// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/survey/send-mail": {
            "post": {
                "description": "Sends a customized survey email to a customer regarding their restaurant experience",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Send a survey email to a customer",
                "parameters": [
                    {
                        "description": "Email request information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message:Survey email sent successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error:Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error:Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.EmailRequest": {
            "description": "Email request information for sending surveys",
            "type": "object",
            "required": [
                "email",
                "name",
                "restaurant"
            ],
            "properties": {
                "email": {
                    "description": "The customer's email address\n@example customer@example.com",
                    "type": "string",
                    "example": "customer@example.com"
                },
                "name": {
                    "description": "The customer's full name\n@example John Doe",
                    "type": "string",
                    "example": "John Doe"
                },
                "restaurant": {
                    "description": "The name of the restaurant visited\n@example The Great Restaurant",
                    "type": "string",
                    "example": "The Great Restaurant"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Survey Email Service API",
	Description:      "API for sending survey emails to customers about restaurant experiences",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
