name: Deploy Email-Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build with Go
        run: |
          go mod download
          go mod tidy
          CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o email-service main.go

      - name: Build Docker image
        run: |
          docker build -t richard28/email-service:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: docker push richard28/email-service:latest

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/key.pem
          chmod 400 /tmp/key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            docker pull richard28/email-service:latest
            
            docker-compose down
            
            docker-compose up -d --remove-orphans
            
            exit
          EOF
